### ISSUE TITLE
Generating JSON file

### ISSUE THREAD

**Issue by geoshar** [timoxley/tojson-loader#1]
This loader just puts a JSON object into the bundle, but how to separate? For example i have a file config.json.js, i want it to be compiled into config.json on the dist folder..Is there a solution?

**Comment by timoxley** [comment]
Curious, why separate? I believe normal webpack code-splitting by defining this as a separate chunk will work.

**Comment by geoshar** [comment]
I have a JS configuration file on the app, and i would like to convert that into JSON file, after that, this JSON configuration file will be parsed/modified with PHP, then will be sent into the app by the html DOM.. That's just something like a default configuration created in JS,and exported for PHP.. Anyway, i've already solved this in a different manner, like i've described here [Webpack compile config.js to config.json](https://stackoverflow.com/questions/47566294/webpack-compile-config-js-to-config-json/47615166#47615166)
Maybe i'm missing something, and there's a way better solution?:)

**Comment by timoxley** [comment]
That's a pretty great solution, it like it.
